---

- name: Install custom defined packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('installed') }}"
    enablerepo: "{{ item.enablerepo | default(omit) }}"
    disable_gpg_check: "{{ item.disable_gpg_check | default(omit) }}"
  with_items:
    - "{{ packages }}"
