---

- name: Packages | Debian | Install custom defined packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('installed') }}"
  with_items:
    - "{{ packages }}"
  loop_control:
    label: "Package: '{{ item.name }}' Will be '{{ item.state|default('installed') }}'"
